import uuid
import logging

from sqlalchemy.ext.asyncio import AsyncSession

from app.models.prediction import Prediction
from app.services.history_service import get_prediction_by_id
from app.llm.client import generate_report
from app.llm.prompts import build_report_prompt, FALLBACK_REPORT
from app.llm.validator import validate_report

log = logging.getLogger(__name__)


async def generate_clinical_report(
    db: AsyncSession,
    prediction_id: uuid.UUID,
    user_id: uuid.UUID,
    patient_age: int | None = None,
    patient_gender: str | None = None,
    patient_symptoms: str | None = None,
) -> tuple[str, str]:
    """
    Generate an LLM-powered clinical report for a prediction.
    Updates the prediction record with the report text and patient context.
    Returns (report_text, provider_name).
    """
    prediction = await get_prediction_by_id(db, prediction_id, user_id)
    if prediction is None:
        raise ValueError(f"Prediction {prediction_id} not found")

    prompt = build_report_prompt(
        prediction=prediction.prediction.value if hasattr(prediction.prediction, 'value') else str(prediction.prediction),
        confidence=prediction.confidence,
        model_version=prediction.model_version,
        gradcam_observation=prediction.gradcam_observation or "No Grad-CAM observation available",
        patient_age=patient_age,
        patient_gender=patient_gender,
        patient_symptoms=patient_symptoms,
    )

    raw_text, provider = await generate_report(prompt)

    if raw_text is None:
        report_text = FALLBACK_REPORT
        provider = "fallback"
    else:
        is_valid, missing = validate_report(raw_text)
        if not is_valid:
            log.warning(
                "LLM report from %s missing sections %s — appending fallback sections",
                provider, missing,
            )
            # Use the raw text anyway but note what's missing
            report_text = raw_text + f"\n\n_Note: Sections {missing} were not generated by the AI._"
        else:
            report_text = raw_text

    # Persist report + patient context
    prediction.report_text = report_text
    if patient_age is not None:
        prediction.patient_age = patient_age
    if patient_gender:
        prediction.patient_gender = patient_gender
    if patient_symptoms:
        prediction.patient_symptoms = patient_symptoms

    await db.flush()

    log.info("Report generated for prediction %s via %s", prediction_id, provider)
    return report_text, provider
