"""
Hospital-grade structured prompt templates for clinical report generation.
Designed to match the high standards of leading diagnostic centers and hospital networks.
"""
from typing import Optional


def build_report_prompt(
    prediction: str,
    confidence: float,
    model_version: str,
    gradcam_observation: str,
    patient_age: Optional[int] = None,
    patient_gender: Optional[str] = None,
    patient_symptoms: Optional[str] = None,
) -> str:
    patient_parts = []
    if patient_age is not None:
        patient_parts.append(f"Age: {patient_age}")
    if patient_gender:
        patient_parts.append(f"Gender: {patient_gender}")
    if patient_symptoms:
        patient_parts.append(f"Presenting Complaints: {patient_symptoms}")

    patient_context = (
        "PATIENT DEMOGRAPHICS & PRESENTING COMPLAINTS:\n" + "\n".join(patient_parts) + "\n"
        if patient_parts else "PATIENT DEMOGRAPHICS & PRESENTING COMPLAINTS: Not specified\n"
    )

    return f"""You are an elite Senior Consultant Radiologist AI generating a formal, hospital-grade
Diagnostic Assessment Report for a Chest Radiograph (Anterior-Posterior view).

DIAGNOSTIC AUTOMATION METRICS:
- Primary AI Classification: {prediction}
- Model Confidence Score: {confidence:.1%}
- Algorithm Engine: EfficientNet-B0 Medical Vision (v{model_version})
- Grad-CAM Heatmap Spatial Localization: {gradcam_observation}

{patient_context}
Generate an authoritative, executive-level medical intelligence report using EXACTLY the following section headings:

## Clinical Summary
Provide a clear, high-level executive summary of the radiographic findings in 2-3 sentences, using formal medical terminology (e.g., parenchymal consolidation, airspace opacity, reticular infiltrates).

## Possible Differential Considerations
List 3-5 clinical differential diagnoses in bullet points (e.g., Bacterial Lobar Pneumonia, Viral Pneumonitis, Atelectasis, Pulmonary Edema, Bronchopneumonia), briefly explaining radiographic overlap.

## Recommended Next Steps
Provide 3-4 structured clinical management and follow-up recommendations (e.g., High-resolution CT, Sputum culture, Inflammatory markers CRP/ESR, Clinical correlation, Follow-up X-ray in 48-72h).

## Limitations of AI Analysis
Detail 2-3 specific technical and clinical limitations of this automated screening evaluation (e.g., inability to distinguish bacterial vs viral etiology from single projection, potential false positives from anatomical overlap).

## Urgency Level
Specify EXACTLY ONE triage category: [ROUTINE], [SEMI-URGENT], or [URGENT], followed by a 1-2 sentence clinical rationale based on confidence and presented symptoms.

## Disclaimer
State a clear, uncompromising clinical and legal disclaimer that this report is generated by an AI decision-support platform, is intended for clinical review and research/demonstration purposes, does not constitute a definitive medical diagnosis, and requires signature/review by a licensed radiologist.

Maintain an articulate, objective, hospital-grade clinical tone throughout. Do not use informal language."""


FALLBACK_REPORT = """## Clinical Summary
Automated radiographic analysis was completed for the submitted Chest Radiograph. The deep learning vision engine classified the image with preliminary findings. Due to temporary LLM gateway latency, a standard structured template has been populated for clinician review.

## Possible Differential Considerations
• Primary differential pending comprehensive multi-modal AI synthesis.
• Clinical correlation with patient clinical history and laboratory markers recommended.
• Radiological confirmation by a licensed physician advised.

## Recommended Next Steps
• Re-trigger report generation or perform manual radiological interpretation.
• Evaluate clinical markers (WBC count, CRP, oxygen saturation).
• Order lateral projection or HRCT if clinical suspicion remains high.

## Limitations of AI Analysis
• This report was populated via automated emergency fallback logic due to LLM provider unavailability.
• Single AP/PA projection limitations apply.

## Urgency Level
ROUTINE — Automated preliminary classification complete; full LLM report generation pending.

## Disclaimer
IMPORTANT NOTICE: This automated screening assessment is produced by an AI decision-support platform for clinical demonstration purposes. It is NOT a diagnostic device and must be reviewed and signed off by a licensed radiologist before clinical management decisions are made."""
